name: Build EXE
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Herramientas
        uses: microsoft/setup-msbuild@v2
      - name: Compilar
        run: csc /target:winexe /out:DominantExecutor.exe executor.cs
      - name: Subir
        uses: actions/upload-artifact@v4
        with:
          name: Dominant-App
          path: DominantExecutor.exe
