name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: csc /target:winexe /out:DominantExecutor.exe Executor.cs
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Dominant-App
          path: DominantExecutor.exe
