name: Build EXE
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compilar
        run: |
          $csc = Get-ChildItem -Path "C:\Windows\Microsoft.NET\Framework" -Filter "csc.exe" -Recurse | Select-Object -First 1 -ExpandProperty FullName
          & $csc /target:winexe /out:DominantExecutor.exe executor.cs
      - name: Subir
        uses: actions/upload-artifact@v4
        with:
          name: Dominant-App
          path: DominantExecutor.exe
